In [ ]:
!pip install gym

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import gym
import numpy as np
import random

In [ ]:
env=gym.make('FrozenLake-v1',new_step_api=True)

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
actionSize = env.action_space.n
stateSize = env.observation_space.n
qTable = np.zeros((stateSize,actionSize))

NameError: ignored

In [ ]:
print(qTable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
episodeNum = 1000000
stepMax = 100
lr = 0.1
dr = 0.99
e = 1
minE = 0.01
maxE = 1
decay = 0.001

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [ ]:
rewards_all_episodes = []
for episode in range(episodeNum):
  state = env.reset()

  done = False
  reward = 0
  for step in range(stepMax):
    if np.random.uniform(0,1) > e:
      action = np.argmax(qTable[state,:])
    else:
      action = env.action_space.sample()

    nState, r, done, _, info = env.step(action)

    qTable[state,action] = (1-lr)*qTable[state,action] + lr*(r+dr*np.max(qTable[nState,:]))
    state = nState
    reward += r
    if done:
      break

  e = maxE * np.exp(-decay*episode)
  rewards_all_episodes.append(reward)

In [ ]:
count = 1000
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes/1000)
for r in rewards_per_thousand_episodes:
  print(count, ":", str(sum(r/1000)))
  count += 1000

1000 : 0.04900000000000004
2000 : 0.20700000000000016
3000 : 0.4100000000000003
4000 : 0.6050000000000004
5000 : 0.6580000000000005
6000 : 0.7140000000000005
7000 : 0.7070000000000005
8000 : 0.7500000000000006
9000 : 0.7220000000000005
10000 : 0.7250000000000005


In [ ]:
for r in rewardsAvg:
  print(sum(r)/len(r))

NameError: ignored